"""empty message

Revision ID: e321dc592a1a
Revises: 229650f624af
Create Date: 2021-02-03 10:40:20.684356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e321dc592a1a'
down_revision = '229650f624af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('copper_value', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('gold_value', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('platinum_value', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('silver_value', sa.Integer(), nullable=True))
    op.drop_column('items', 'platinum')
    op.drop_column('items', 'gold')
    op.drop_column('items', 'silver')
    op.drop_column('items', 'copper')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('copper', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('silver', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('gold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('platinum', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('items', 'silver_value')
    op.drop_column('items', 'platinum_value')
    op.drop_column('items', 'gold_value')
    op.drop_column('items', 'copper_value')
    # ### end Alembic commands ###
